"""drop email column from users

Revision ID: 92c9af4c36f0
Revises: b25bcc5cfb58
Create Date: 2026-07-26 19:04:43.174842

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92c9af4c36f0"
down_revision: str | Sequence[str] | None = "b25bcc5cfb58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
